### ISSUE TITLE
cuda版本的配置在哪个文件？Check failed: error == cudaSuccess (803 vs. 0)  system has unsupported display driver / cuda driver combination

### ISSUE THREAD

**Issue by panguxiaoshen** [eric612/MobileNet-YOLO#266]
2080ti, cuda10.1, 在nvidia-docker下搭的环境。nvidia-smi是正常的
Check failed: error == cudaSuccess (803 vs. 0)  system has unsupported display driver / cuda driver combination

**Comment by ruabuliuqiu** [comment]
解决了吗？我跑caffe runtest时，报同样的错误

**Comment by dreamercv** [comment]
` Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device`我也出现了错误，请问您解决了me
